[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"

[build.environment]
    NETLIFY_LAMBDA_JS_FUNCTION = "server"